const usernames = [
    'michael',
    'jim',
    'pam',
    'dwight',
    'phyllis',
    'stanley',
    'merideth',
    'angela',
    'oscar',
    'kevin',
    'toby',
    'andy',
    'erin',
    'darryl',
    'kelly',
    'holly',
    'creed',
]

const emails = [
    'michael@me.com',
    'jim@me.com',
    'pam@me.com',
    'dwight@me.com',
    'phyllis@me.com',
    'stanley@me.com',
    'merideth@me.com',
    'angela@me.com',
    'oscar@me.com',
    'kevin@me.com',
    'toby@me.com',
    'andy@me.com',
    'erin@me.com',
    'darryl@me.com',
    'kelly@me.com',
    'holly@me.com',
    'creed@me.com',
]

const thoughts = [
    "Sometimes I'll start a sentence and I don't even know where it's going. I just hope I find it along the way.",
    "Whenever I'm about to do something, I think, 'Would an idiot do that?' and if they would, I do not do that thing.",
    "I knew exactly what to do, but in a much more real sense I had no idea what to do.",
    "Identity theft is not a joke, Jim! Millions of families suffer every year.",
    "One day Michael came in and complained about a speed bump on the highway. I wonder who he ran over then.",
    "I understand nothing.",
    "I wish there was a way to know you're in the good old days before you've actually left them.",
    "I am Beyoncé, always.",
    "I talk a lot, so I've learned to just tune myself out...",
    "Sorry I annoyed you with my friendship.",
    "I'm not superstitious, but I am a little stitious.",
    "If I don't have some cake soon, I might die.",
    "I am faster than 80 percent of all snakes.",
    "I hate the idea that someone out there hates me. I even hate thinking that al-Qaeda hates me. I think if they got to know me, they wouldn’t hate me.",
    "Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.",
    "I’m an early bird and I’m a night owl so I’m wise and I have worms.",
    "Bears, beets, Battlestar Galactica.",
    "I consider myself a good person, but I'm gonna try to make him cry.","The worst thing about prison was the Dementors.",
    "Sometimes the clothes at Gap Kids are just too flashy.",
    "Dwight mercy-killed Angela’s cat.",
    "Guess what, I have flaws. What are they? Oh, I don't know. I sing in the shower. Sometimes I spend too much time volunteering. Occasionally I'll hit somebody with my car. So sue me... No, don't sue me. That is the opposite of the point that I'm trying to make.",
    "I am about to do something very bold in this job that I’ve never done before: try.",
    "I miss the days when there was only one party I didn't want to go to.",
    "Me think, why waste time say lot word, when few word do trick.",
    "I love inside jokes. I’d love to be a part of one someday.",
    "Do I need to be liked? Absolutely not. I like to be liked. I enjoy being liked. I have to be liked, but it’s not like this compulsive need to be liked, like my need to be praised.",
    "Oh, you’re paying way too much for worms. Who’s your worm guy?",
    "I’m glad Michael’s getting help. He has a lot of issues, and he’s stupid",
    "I don’t hate it. I just don’t like it at all and it’s terrible.",
    "You guys I’m, like, really smart now. You don’t even know. You could ask me, 'Kelly, what’s the biggest company in the world?' And I’d be like, 'blah blah blah, blah blah blah blah blah blah.' Giving you the exact right answer.",
    "When you’re a kid, you assume your parents are soulmates. My kids are going to be right about that.",
    "If I don’t have some cake soon, I might die.",
    "I don’t want to be married in a tent like a hobo.",
    "Who says exactly what they’re thinking? What kind of a game is that?",
    "I’ve been involved in a number of cults, both a leader and a follower. You have more fun as a follower, but you make more money as a leader.",
    "Sometimes I get so bored I just want to scream, and then sometimes I actually do scream. I just sort of feel out what the situation calls for.",
    "If I can’t scuba, then what’s this all been about? What am I working toward?",
    "Dwight, you ignorant slut.",
    "I mean, I’m not a slut, but who knows.",
    "Close your mouth, sweetie. You look like a trout.",
    "Nobody steals from Creed Bratton and gets away with it. The last person to do this disappeared. His name? Creed Bratton.",
    "Tell ya one thing, I’m not gonna be a good mom tonight.",
    "Boy, have you done lost your mind? Cause I’ll help you find it!",
    "I talk a lot, so I’ve learned to tune myself out.",
]

module.exports = { usernames, emails, thoughts };